### ISSUE TITLE
flask, flask_cors, request

### ISSUE THREAD

**Issue by SkorpionBG** [massiveschlong/onlyfans-content-downloader#1]
Hello, bro I have a problem with the flasks, can you help me to fix it? Thanks!

from flask import Flask, request
from flask_cors import CORS
import requests

![Screenshot 2022-02-10 110520](https://user-images.githubusercontent.com/75161513/153373814-9bf1c474-4e2a-4aba-b6f9-bb72d9beb334.png)
![Screenshot 2022-02-10 110720](https://user-images.githubusercontent.com/75161513/153374149-11cb986a-143e-455e-a0a0-cee6f566c4dd.png)

**Comment by massiveschlong** [comment]
Yo, you need to install the dependencies on your machine.

https://github.com/massiveschlong/onlyfans-content-downloader#dependencies
