### ISSUE TITLE
hey please help

### ISSUE THREAD

**Issue by Mou3az** [massiveschlong/onlyfans-content-downloader#10]
hi i came across this code by typing "onlyfans downloader" on the internet, i don't know anything about coding and python or anything else but i really need help please it's important, do you have instagram or any network where we can talk about my problem because i can't download the content, i can even pay you with all i have if you want lol.
Anyway I hope you will help me thank you very much!

**Comment by Mou3az** [comment]
my discord: mouaz#5505

**Comment by massiveschlong** [comment]
hi @Mou3az, i sent you a friend request.
