### ISSUE TITLE
Doesn't Download Anything

### ISSUE THREAD

**Issue by dinosaw** [massiveschlong/onlyfans-content-downloader#2]
I'm using Python 3.10 and have the `download_content.py` script up in a console with no errors showing:

```
 * Serving Flask app 'download_content' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 711-680-843
```

When I go to the OF profile and paste the javascript into the console, it simply redirects the page to /profile/media and then does nothing. The console shows the following:

```
VM699:106 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'innerText')
    at <anonymous>:106:44
    at new Promise (<anonymous>)
    at fetchContent (<anonymous>:99:10)
    at autoClicker (<anonymous>:116:11)
```

What is supposed to happen after you execute the javascript? Does a button pop up somewhere? Or just the Windows dialogue box? I'm not sure what is to be expected after this.

**Comment by massiveschlong** [comment]
Hey, apparently, OF updated their site and it broke the JS code!
I updated everything, please retry! :)
