### ISSUE TITLE
Please clarify how to find all JavaScript to copy?

### ISSUE THREAD

**Issue by Koalamanx** [massiveschlong/onlyfans-content-downloader#4]
Please clarify how to find all JavaScript to copy? After going into developer tools, what then?

**Comment by massiveschlong** [comment]
Did you read the readme file? 

There is no "other" JavaScript code to be found. All the necessary JavaScript code is provided.

**Comment by Koalamanx** [comment]
I promise I read the file multiple times the bit that I don't understand is
why use a copy JavaScript karma what I don't understand is which part to
copy where when I'm in the developers console how do I get to that
JavaScript bit that I need to copy?

**Comment by massiveschlong** [comment]
It says in the readme file to copy ALL the JavaScript code, not part of it.

All the JavaScript code can be found in the ".js" file.
You copy and paste that in the browser console as shown on the image and then press ENTER to execute the JS code.

Does that clarify your question?

**Comment by Koalamanx** [comment]
Thanks so much for all your help!

Now I understand the problem, yes you did specifically state what to do,
the bit that I didn't understand was that there actually is already a
fetch.JS file in the folder to open copy and then insert into the web
console, my understanding from reading the readme file was that I was
supposed to copy some form of JavaScript which was to be found in the
actual development console copy that and then insert that into the web
console.

Now that I've understood that I actually need to copy the JavaScript file
coded by you and insert that into the web console it'll make sense and it
looked like it all started downloading.

Where does it download to?

**Comment by Koalamanx** [comment]
Ok from looking at what is actually happening I'm understanding that a new
page is supposed to open or I can download content?

I get this:

**Comment by massiveschlong** [comment]
Hi, 

no problem.

No new page is supposed to open. The content downloads via the Python backend code that should have been ran in step 1.

The JS sends the fetched content to the Python file for download.

I might reply slow because I'm busy now, sorry!

Hope you can figure it out meanwhile.

**Comment by Koalamanx** [comment]
All good mate! I finally got it to work!

So basically the 3 things that sort of got me, were that I didn't
understand by reading the readme file that I need to copy the JS code from
the fetch file the second thing was which is totally my mistake that cause
I was so confused I forgot to run the first step in the first place and the
third thing which I noticed which really helps is going back to Visual
Studio code and watching it download and you can see them where are
downloads to namely the subscription folder.

Thanks so much for your help!

**Comment by massiveschlong** [comment]
Hi, great you figured it out and thanks for the feedback!

> that I need to copy the JS code from the fetch file
Addressed your feedback, updated readme file.

> the second thing was which is totally my mistake that cause I was so confused I forgot to run the first step in the first place
No worries!

> the third thing which I noticed which really helps is going back to Visual Studio code and watching it download
I added code that will now inform the user where to look for the download progression.

>  and you can see them where are downloads to namely the subscription folder.
I added code that will tell the user in both the browser output and in the backend terminal where the downloaded content is located.

Hope that helps!

Thanks again for the feedback. Let me know if I can close this ticket.
If no response for 3 days I will auto close it.
