### ISSUE TITLE
Cant download videos

### ISSUE THREAD

**Issue by kevinRAM99** [massiveschlong/onlyfans-content-downloader#7]
` Download process for videos skipped because @generiuser didn't post any.`

But the user have videos.. just avatar and banner downloaded

**Comment by massiveschlong** [comment]
Did you download the latest commit? If you are unsure then please download the latest commit. 

If the problem still persists after that let me know, because it works for me.

**Comment by kieeeee24Self** [comment]
Yep.. directly from master.zip

**Comment by kieeeee24Self** [comment]
![image](https://user-images.githubusercontent.com/110026884/181627451-1775369a-cbc1-4d68-a0a0-485ad870aba6.png)

**Comment by kieeeee24Self** [comment]
![image](https://user-images.githubusercontent.com/110026884/181628066-07abe18a-2f2e-4cda-81a1-b8202ed196ef.png)

in firefox

**Comment by massiveschlong** [comment]
Can you post your JavaScript code?
I will check out the problem in 1-2 hours from now

**Comment by kieeeee24Self** [comment]
`clear();
{
	// Configuration.
	const config = {
		'avatar': {
			'download': true,
			'element': () => document.getElementsByClassName("g-avatar")[3],
			'fetch': () => fetchAvatar()
		},
		'banner': {
			'download': true,
			'element': () => document.getElementsByClassName('b-profile__header__cover-img')[0],
			'fetch': () => fetchBanner()
		},
		'photos': {
			'download': false,
			'iterationSpeedDelayInSeconds': 0,  // How fast the app will iterate over the media content. 0 means instantly.
			'scrollIntervalDelayInSeconds': 0,  // The delay time between each scroll interval.
			'scrollExtentInMinutes': 0, // 0 means download everything.
			'content': () => document.getElementsByClassName('pswp__img'), // The currently opened grid photo.
			'source': element => element.src, 
			'fetch': mediaType => loadPhotoVideo(mediaType),
			'element': () => {  // The "Photo <<N>> button-tab."
				for(element of document.getElementsByClassName('b-tabs__nav__text')) {
					if (element.outerText.match("Photo")) return element;
				}
			}
		},
		'videos': {
			'download': true,
			'iterationSpeedDelayInSeconds': 0.2,
			'scrollIntervalDelayInSeconds': 0,
			'scrollExtentInMinutes': 0, // 0 means download everything.
			'content': () => document.getElementsByClassName('vjs-tech'),
			'source': element => element.firstElementChild.src, 
			'fetch': mediaType => loadPhotoVideo(mediaType),
			'element': () => {  // The "Photo <<N>> button-tab."
				for(element of document.getElementsByClassName('b-tabs__nav__text')) {
					if (element.outerText.match("Video")) return element;
				}
			}
		},
		'archived': {
			'download': false,
			'element': () => document.getElementsByClassName('b-tabs__nav__link__counter-title')[2]
		},
	};

	// Load next content section of page.
	function loadContent () {
		const loadBtn = document.getElementsByClassName('g-btn m-rounded m-block w-100')[0]
		if (loadBtn) loadBtn.click()
	}

	// Global variables.
	const profiles = {}; // Store content-creator storage object.
	const username = window.location.pathname.split('/')[1]; // Username of content-creator.
	const media = document.getElementsByClassName('b-tabs__nav__link__counter-title')[1]; // Media tab.

	// Current URL pathname.
	function pathname () {
		const pathname = window.location.pathname.split('/').slice(-1)[0];
		return pathname[pathname.length - 1].toLocaleLowerCase();
	}

	// Freeze/pauze/sleep the code for a certain amount of time.
	function freeze (time = 3000) { return new Promise(resolve => setTimeout(() => { resolve(true); }, time)); }

	// Current page offset height in percentages.
	function pageYOffsetPercentage() { return Math.round((window.innerHeight + window.pageYOffset) / document.body.offsetHeight * 100); }

	// Get the current media type.
	function currentMediaType() {
		return window.location.href.split('/').slice(-1)[0];
	}

	// Scroll to bottom.
	function scrollToBottom (scrollIntervalDelayInSeconds = 1, scrollExtentInMinutes = 0) {
		console.info('⌛ Page scroll in progress...');
		
		// Stop scroll early if user specified scroll extent in minutes.
		let scrollLimitTimer; scrollActive = true;
		if (scrollExtentInMinutes !== 0) {
			console.warn(`⚠️ Scrolling for ${currentMediaType()} will not take any longer than ${scrollExtentInMinutes} minute(s) because of the set configuration.`);
			scrollLimitTimer = setTimeout(() => scrollActive = false, scrollExtentInMinutes * 1000 * 60);
		}

		let currentPageYOffset = pageYOffsetPercentage();
		return new Promise (async resolve => {
			while (scrollActive) {
				// Scroll down.
				window.scrollTo(0, document.body.scrollHeight);
				await freeze(scrollIntervalDelayInSeconds * 1000 + 1000); // The "+ 1000" is a safety mechanism to make sure the "loading icon" on the page appears.
				if (window.getComputedStyle(document.getElementsByClassName('infinite-status-prompt')[0]).display !== 'none') { continue; }  // Check if page is still loading for content.
				if (document.getElementsByClassName('g-btn m-rounded m-block w-100')[0]) { document.getElementsByClassName('g-btn m-rounded m-block w-100')[0].click(); continue; }  // Check if manual load button appeared on the page.
				const newPageYOffset = pageYOffsetPercentage();  // Get the new Y scroll offset of the page.
				if (newPageYOffset > currentPageYOffset) { currentPageYOffset = newPageYOffset; continue; }  // Update page Y offset.
				if (currentPageYOffset !==  100 && newPageYOffset !== 100) { continue; } // Check if page scroll is complete. Continue if not.
				break;  // Page is done scrolling from 0 to 100.
			}
			clearTimeout(scrollLimitTimer);  // Clear the timeout, content can finish before timer reaches limit.
			scroll(0, 0); console.info('✔️ Finished scrolling page.'); resolve(true);
		});
	}

    // Fetch avatar/banner.
	function fetchAvatar () { profiles[username].avatar.sources.push(config.avatar.element().firstChild.src.replace('thumbs/c144/', '')); }
	function fetchBanner () { profiles[username].banner.sources.push(config.banner.element().src.replace('thumbs/w480/', '')); }

	// Fetch photo/video.
	function loadPhotoVideo(mediaType) {
		return new Promise (async resolve => {
			const media = config[mediaType]; const profileMedia = profiles[username][mediaType];
			let progress = 0; let currentProgressInPercentage = 0; newProgressInPercentage = 0; let downloaded = 0; media.element().click(); await freeze(1000);
			await scrollToBottom(config[mediaType].scrollIntervalDelayInSeconds, config[mediaType].scrollExtentInMinutes);
			firstItem = document.getElementsByClassName('b-photos__item__img')[0];
			if (!firstItem) { console.warn(`⚠️ No downloadable ${mediaType}.`); return resolve(true); }
			firstItem.click(); await freeze(1000);
			while (profileMedia.amount > progress) {
				progress += 1; newProgressInPercentage = Math.round(progress / profileMedia.amount * 100);
				if (newProgressInPercentage > currentProgressInPercentage) {
					currentProgressInPercentage = newProgressInPercentage;
					console.info(`⌚ [${mediaType.toUpperCase()}]`, currentProgressInPercentage + "%");
				}

				for (let i = 0; i < media.content().length; i++) {
					const item = media.source(media.content()[i]); const profileMediaTypeSources = profileMedia.sources;
					if (item && !profileMediaTypeSources.includes(item)) {
						profileMediaTypeSources.push(item); downloaded++;
					}
					document.getElementsByClassName('pswp__button pswp__button--arrow--right')[0].click();
					await freeze(media.iterationSpeedDelayInSeconds * 1000);
				}
			}
			if (config[mediaType].scrollExtentInMinutes !== 0) { console.warn(`⚠️ ${profileMedia.amount - downloaded} undownloaded for ${mediaType} because the max scroll extent for it was set to ${config[mediaType].scrollExtentInMinutes} minutes.`); }
			else { console.warn(`🔒 ${profileMedia.amount - downloaded} locked/hidden for ${mediaType}.`); }
			profileMedia.amount = downloaded; resolve(true); 
		});
	}
 
	// Fetch content.
	function fetchContent () {
		return new Promise (async resolve => {
			profiles[username] = {}; const keys = Object.keys(config); const index = keys.indexOf(pathname());
			if (index !== -1) { [keys[0], keys[index]] = [keys[index], keys[0]]; }
			for (const o of keys) {
				if (!config[o].download) continue;
				const currentMediaElement = config[o].element();
				if (!currentMediaElement) {
					console.warn(`⚠️ Download process for ${o} skipped because @${username} didn't post any.`);
					continue;
				}
				profiles[username][o] = {
					'sources': [],
					'amount': parseInt(currentMediaElement.innerText.replace(/\D/g, ''))
				}; if (config[o].fetch) await config[o].fetch(o);
			} resolve(true);
		});
	}

	function downloadContentRequest () {
		fetch('http://127.0.0.1:5000/download_content', { // Send content to the server for download.
			method: 'POST', mode: 'cors', headers: { 'Content-Type': 'application/json;charset=utf-8' },
			body: JSON.stringify({ [username]: profiles[username] })
		}).then(response => response.text()).then(rv => console.info(rv));
	}

	// Auto clicker.
	async function autoClicker() {
		if (!document.getElementsByClassName('b-tabs__nav__item m-current')[0].firstChild.href.split('/')[4]) {
			media.click(); await freeze(); // Click media tab.
		} await fetchContent(); await freeze(1000); // Freeze the code so the page can load.
		document.getElementsByClassName('pswp__button pswp__button--close')[0].click();
		console.log("↪️ Check the backend code terminal output for the download status.")
		downloadContentRequest();
	}

	// Execute the code.
	autoClicker();
}`

**Comment by kieeeee24Self** [comment]
https://paste.ofcode.org/L6WeYKMiKv4mk4zcDxf9Ae

**Comment by massiveschlong** [comment]
Hi, I tested your code and it works fine on my machine. You said you were using Firefox, and so am I.
If you have Discord we can continue the conversation over there? Because I might have to ask you many more questions to solve this for you.

**Comment by vartiel** [comment]
Were you able to fix the problem? I am also having the same problem.

**Comment by massiveschlong** [comment]
Hi @kieeeee24Self, do you have an update for me? So I can keep this ticket open or close it

**Comment by kieeeee24Self** [comment]
I'll try again, I'll tell you what happens.

**Comment by funkeymonkey17** [comment]
I've also been unable to download anything

This is what happens at the end: 

![CleanShot 2022-09-18 at 13 50 27](https://user-images.githubusercontent.com/71237087/190921385-b4405597-defe-43ac-a512-593c13dd4a20.png)

Do you have discord I could add?

**Comment by massiveschlong** [comment]
Hi, sorry for the slow reply. Seems to be an issue on your machine. Sorry for the bold statement but the code works on my machine.

Maybe this helps: https://www.google.com/search?client=firefox-b-d&q=request+has+no+attribute+get

Let me know if this solves your issue.

**Comment by zhudybb** [comment]
Hi, thank you for sharing the work. I had some trouble when page scrolling. 
Uncaught (in promise) TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at <anonymous>:94:16
Have a nice weekend.

**Comment by massiveschlong** [comment]
Hey sorry for not getting back to you @zhudybb & @kevinRAM99, I'm working on it right now, have been busy lately.
Will close this thread when the issue has been resolved.

**Comment by massiveschlong** [comment]
hey @zhudybb @kevinRAM99, the issue has been resolved, feel free to reopen if you experience problems
tested on firefox 108.0.2 (64-bits)
